baseURL = 'https://joma0.github.io/labveilletech/'
languageCode = 'fr-ch'
title = 'Joanah Mayor | Veille technologique'
author = 'Joanah Mayor' 
[pagination]
  pagerSize = 2


# ------------------------------
theme = "hugo-paper"

# ------------------------------
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

